services:
  jboss:
    image: quay.io/wildfly/wildfly
    ports:
      - 8084:8080
    volumes:
      - ./target/mypack-1.0-SNAPSHOT.war:/opt/jboss/wildfly/standalone/deployments/ROOT.war
    depends_on:
      - DBsql
  DBsql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 654321
      MYSQL_DATABASE: mypack
    volumes:
      - dbmypack:/var/lib/mysql
    ports:
      - 3307:3306
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80
    environment:
      - PMA_HOST=DBsql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=654321
    depends_on:
      - DBsql
volumes:
  dbmypack: